platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: 8.7-jdk17

inputs:
  - name: sample-app-repo

run:
  path: sh
  args:
    - -exc
    - |
      cd sample-app-repo
      chmod +x gradlew
      ./gradlew clean build --no-daemon --stacktrace --info
